spring:
  application:
    name: library-service
  data:
    mongodb:
      #port: 0
      #database: test
      host: localhost
      port: 27017
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.changelogs

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, logfile, loggers, metrics, hystrix.stream
    info:
      env:
        enabled: true
  endpoint:
    health:
      show-details: always

info:
  app:
    version: 1.0
    authors: Konstantin Nazarov
    description: Web app with actuator

hystrix:
  command:
    readFromDbKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    otherDbOperationKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
  dashboard:
    proxy-stream-allow-list: "*"

logging:
  level:
    root: INFO

    org:
      springframework:
        web: INFO
        security: INFO

      mongodb: INFO

  file:
    name: application.log