spring:
  datasource:
    url: jdbc:h2:mem:testdb
    show-sql: false

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    root: ERROR

shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED