spring:
  data:
    mongodb:
      #port: 0
      #database: test
      host: localhost
      port: 27017
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.changelogs

logging:
  level:
    root: ERROR

shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED