spring:
  messages:
    basename: i18n/messages
  banner:
    location: ./banner_new.txt
  output:
    ansi:
      enabled: always

i18n:
  locale: "ru_RU"

csv:
  resourcePath: ./questions.csv
  separator: ","
  ignoreQuotations: false
  skipLines: 1

quiz:
  countAnswersForPassing: 3